# -*- coding: utf-8 -*-
"""Fibonacci_Generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FEjmQBcDNfB_0TA_NRyAFUgJDgn2IMRd
"""

# Generator to produce Fibonacci sequence up to 'n' terms
def fibonacci_generator(n):
    a, b = 0, 1
    count = 0
    while count < n:
        yield a
        a, b = b, a + b
        count += 1

# Input validation and handling
def get_fibonacci_sequence():
    try:
        n = int(input("Enter the number of terms: "))
        if n <= 0:
            raise ValueError("The number must be a positive integer.")
    except ValueError as e:
        print(f"Invalid input: {e}")
        return

    print(f"The first {n} terms of the Fibonacci series are:")
    for num in fibonacci_generator(n):
        print(num, end=" ")
    print()

# Call the function to get the Fibonacci sequence
get_fibonacci_sequence()

